# Site settings
title: Kritika Jalan, Personal website
tag_text: Kritika Jalan
description: Kritika Jalan, Data scientist having work-ex with Australia's one of the largest Telcom company & US' one of the largest Pharma company

# Build settings
markdown: kramdown
exclude: ["README.md"]
sass:
  style: compressed
