# Site settings
title: Kritika Jalan - Data Scientist
tag_text: Kritika Jalan
description: Have worked with Telcos, Pharmacos, Tech Giants and Retailers across the globe.

# Build settings
markdown: kramdown
exclude: ["README.md"]
sass:
  style: compressed
